targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      json_serializable:
        generate_for:
          - lib/apis/**/**.dart
      freezed:
        generate_for:
          - lib/apis/**/**.dart
      go_router_builder:
        generate_for:
          - lib/app/router/router.dart
      drift_dev:
        generate_for:
          - lib/core/storage/db.dart
          - lib/core/storage/schemas/*.drift
        options:
          # 生成代码更少，通常也会更快
          skip_verification_code: true
          data_class_to_companions: false